/**
 * Centralized User-Facing Copy & Messaging Constants
 * Prevents developer jargon, file names, or internal implementation details from leaking into the UI.
 */

export const UI_COPY = {
  studyArena: {
    lockedTrackTitle: (title: string) => `${title} is Locked`,
    lockedTrackDescription: 'This course track is currently locked. Complete the prerequisite modules to unlock access.',
    loadingCourseContent: 'Loading course content...',
    playlistUnavailable: 'Course playlist is currently unavailable. Please try again later.',
    embeddedPlayerNotice: 'You can still view the video playlist directly below.',
    noLecturesFound: (query: string) => `No course lectures match your search "${query}". Try searching with a different term.`,
    viewMoreLectures: (current: number, total: number) => `View More Lectures (${current} of ${total})`,
    showAllLectures: (total: number) => `Show All (${total} Items)`,
    collapseLectures: 'Collapse List (Top 15)',
  },
  registrations: {
    downloadingPass: (eventTitle: string) => `Downloading e-Pass for ${eventTitle}...`,
  },
  playlist: {
    invalidUrl: 'Course playlist is currently unavailable. Please try again later.',
  },
  projects: {
    statusOpen: 'Open',
    statusClosed: 'Closed',
    statusComingSoon: 'Coming Soon',
    noContributors: 'No contributors yet',
    singularContributor: '1 contributor',
    pluralContributors: (count: number) => `${count} contributors`,
    spotsFilled: (current: number, max: number) => `${current} / ${max} spots filled`,
    closesDate: (dateStr: string) => `Closes ${dateStr}`,
    closedDeadline: 'Closed',
    viewDetails: 'View Details',
    contributeNow: 'Contribute to this Project',
    alreadySubmitted: 'Submitted',
    submissionsFull: 'Project Full',
    submissionsClosed: 'Submissions Closed',
    comingSoonButton: 'Coming Soon',
    modalAbout: 'About Project',
    modalGoals: 'Key Project Goals',
    modalRequirements: 'Requirements & Prerequisites',
    modalTechStack: 'Tech Stack',
    modalContributors: 'Project Team & Contributors',
    modalDeadline: 'Deadline & Allowed Submission Types',
    selectProjectLabel: 'Select Project to Contribute',
    selectTypeLabel: 'Submission Type',
    typeIdea: 'Idea Proposal',
    typeTextFile: 'Text / Markdown File',
    typeGithub: 'GitHub Repository',
    ideaTitleLabel: 'Proposal Title',
    ideaTitlePlaceholder: 'e.g., Implementing Convolutional Feature Extractor',
    ideaDetailLabel: 'Proposal Details & Scope',
    ideaDetailPlaceholder: 'Explain your proposed contribution, methodology, and expected outcomes (minimum 100 characters)...',
    ideaMinCharError: 'Proposal details must be at least 100 characters long.',
    fileUploadLabel: 'Upload File (.txt, .md only, max 1 MB)',
    fileUploadBtn: 'Choose File',
    fileTypeError: 'Invalid file format. Please upload a .txt or .md file.',
    fileSizeError: 'File size exceeds the 1 MB limit. Please select a smaller file.',
    githubRepoLabel: 'GitHub Repository URL',
    githubRepoPlaceholder: 'https://github.com/owner/repository',
    githubInvalidError: 'Please enter a valid GitHub repository URL (e.g., https://github.com/owner/repository).',
    nameLabel: 'Full Name',
    namePlaceholder: 'Enter your full name',
    emailLabel: 'Email Address',
    emailPlaceholder: 'name@example.com',
    whyContributeLabel: 'Why do you want to contribute?',
    whyContributePlaceholder: 'Briefly share your experience or interest in this domain (optional)...',
    submitBtn: 'Submit Proposal',
    submittingBtn: 'Submitting Proposal...',
    successTitle: 'Submission Received!',
    successMessage: 'Your submission was received. The team will review it and get back to you.',
    duplicateSubmissionError: 'You have already submitted a contribution proposal for this project using this email address.',
    closeBtn: 'Close',
  }
};
